version: "3"

services:
  web:
    container_name: ${WEB_CONTAINER_NAME}
    restart: always
    build: .
    ports:
      - "${WEB_PORT}:3000"
    links:
      - "db"
    volumes:
      - '${WEB_APP_VOLUME_PATH}:/usr/src/app'
    command: bash -c "npm install && npm run dev"
  db:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: ${MYSQL_CONTAINER_IMAGE}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
    - "${DB_PORT}:3306"